# Generated by Django 3.2.4 on 2023-03-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='Description',
        ),
    ]
