# Generated by Django 3.2.4 on 2023-03-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_task_description_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
