# Generated by Django 4.1.7 on 2023-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
