# Generated by Django 4.1.7 on 2023-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='opt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
